# Generated by Django 2.2.5 on 2020-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclassyear',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
