# Generated by Django 2.2.13 on 2021-01-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_unit', '0007_auto_20210118_1438'),
        ('learning_unit', '0007_auto_20210115_1314'),
    ]

    operations = [
    ]
