env:
  global:
    - CC_TEST_REPORTER_ID=6616c6e25065bb63a246ac0540dbc30acb39d4d2a792adb02110283b4194b6fe

language: python
python: "3.5.5"
cache: pip

install:
  - "pip install -r requirements.txt"

before_script:
  - "psql -d template1 -c 'create extension unaccent;' -U postgres"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script: "python3 manage.py compilemessages && coverage run manage.py test --exclude-tag=selenium --no-logs"

after_script:
  - "coverage xml"
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

services:
  - rabbitmq
addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
