# Generated by Django 2.2.5 on 2019-10-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial_squashed_0012_auto_20180807_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translatedtext',
            unique_together={('entity', 'reference', 'text_label', 'language')},
        ),
    ]
