# Generated by Django 2.2.10 on 2020-03-19 20:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0508_auto_20200319_2005'),
        ('education_group', '0005_auto_20200128_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_child', models.BooleanField(default=False)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ALL', 'ALL'), ('IUFC', 'IUFC'), ('DOCTORAT', 'DOCTORAT')], max_length=200), blank=True, size=None)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'verbose_name': 'Faculty manager',
                'verbose_name_plural': 'Faculty managers',
            },
        ),
    ]
