# Generated by Django 2.2.10 on 2020-06-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0007_auto_20200416_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centraladmissionmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Person'),
        ),
    ]
