# Generated by Django 3.1.1 on 2020-10-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0539_auto_20201006_1045'),
        ('education_group', '0009_remove_groupyear_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centraladmissionmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity'),
        ),
        migrations.AlterField(
            model_name='centralmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity'),
        ),
        migrations.AlterField(
            model_name='facultymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
    ]
