# Generated by Django 2.2.13 on 2021-01-26 08:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0015_auto_20210118_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupyear',
            name='remark_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='remark in english'),
        ),
        migrations.AlterField(
            model_name='groupyear',
            name='remark_fr',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='remark'),
        ),
    ]
