# Generated by Django 2.2.13 on 2021-01-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_group', '0016_auto_20210126_0836'),
        ('education_group', '0016_auto_20210129_0901'),
    ]

    operations = [
    ]
