# Generated by Django 2.2.5 on 2019-12-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('rules_management', '0001_initial'), ('rules_management', '0002_auto_20180824_1458'), ('rules_management', '0003_auto_20180830_1558')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('context', models.CharField(blank=True, choices=[('TRAINING_DAILY_MANAGEMENT', 'Training management day-to-day'), ('TRAINING_PROPOSAL_MANAGEMENT', 'Training management during proposal stage'), ('TRAINING_PGRM_ENCODING_PERIOD', 'Training management during program type encoding period'), ('MINI_TRAINING_DAILY_MANAGEMENT', 'Mini-training management day-to-day'), ('MINI_TRAINING_PROPOSAL_MANAGEMENT', 'Mini-training management during proposal stage'), ('MINI_TRAINING_PGRM_ENCODING_PERIOD', 'Mini-training management during program type encoding period'), ('GROUP_DAILY_MANAGEMENT', 'Group management day-to-day'), ('GROUP_PROPOSAL_MANAGEMENT', 'Group management during proposal stage'), ('GROUP_PGRM_ENCODING_PERIOD', 'Group management during program type encoding period')], max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission')),
                ('groups', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
        ),
    ]
