# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial_squashed_0021_auto_20190128_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainIsced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('title_fr', models.CharField(db_index=True, max_length=255)),
                ('title_en', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'verbose_name': 'The International Standard Classification of Education (ISCED)',
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('-decree__name', 'code', 'name')},
        ),
    ]
