# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-12 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial_squashed_0021_auto_20190128_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ('-decree__name', 'code', 'name')},
        ),
    ]
