# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190312_1141'),
        ('reference', '0002_auto_20190308_1450'),
    ]

    operations = [
    ]
