# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals

from django.db import migrations

from reference.migrations.utils.uuid import set_uuid_field


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_add_uuid_field'),
    ]

    operations = [
        migrations.RunPython(set_uuid_field),
    ]
