openapi: 3.0.0
servers:
 - url: https://{environment}.osis.uclouvain.be/api/v1/program_management/
   variables:
     environment:
       default: dev
       enum:
         - dev # Development server
         - qa # Staging server
         - test # Test server
 - url: https://osis.uclouvain.be/api/v1/program_management/
   description: Production server
info:
  version: '1'
  title: Program Management Service
  description: |-
    A set of API endpoints that allow you to get, update, delete an education group.
paths:
  /trainings/{year}/{acronym}/{version_name}/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the training version
      operationId: training_prerequisites_version
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: version_name
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - trainings
  /trainings/{year}/{acronym}/{version_name}/transition/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the training version (transition)
      operationId: training_prerequisites_version_transition
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: version_name
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - trainings
  /trainings/{year}/{acronym}/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the training (standard version)
      operationId: training_prerequisites_official
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - trainings
  /trainings/{year}/{acronym}/transition/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the training (standard version transition)
      operationId: training_prerequisites_transition
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - trainings
  /mini_trainings/{year}/{acronym}/{version_name}/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the mini-training version
      operationId: mini-training_prerequisites_version
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: version_name
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - mini_trainings
  /mini_trainings/{year}/{acronym}/{version_name}/transition/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the mini-training version transition
      operationId: mini-training_prerequisites_version_transition
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: version_name
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - mini_trainings
  /mini_trainings/{year}/{acronym}/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the mini-training (standard version)
      operationId: mini-training_prerequisites_official
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - mini_trainings
  /mini_trainings/{year}/{acronym}/transition/prerequisites:
    get:
      description: Return the prerequisites of the learning units of the mini-training (standard version transition)
      operationId: mini-training_prerequisites_transition
      parameters:
        - in: path
          name: year
          required: true
          schema:
            description: ''
            type: string
        - in: path
          name: acronym
          required: true
          schema:
            description: ''
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfProgramTreePrerequisites'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - mini_trainings
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    ArrayOfProgramTreePrerequisites:
      type: array
      items:
        $ref: '#/components/schemas/ProgramTreePrerequisites'
    ProgramTreePrerequisites:
      type: object
      properties:
        url:
          type: string
          format: uri
        code:
          type: string
        title:
          type: string
        prerequisites_string:
          type: string
          example: (codeA OR codeB) AND (codeC)
        prerequisites:
          type: array
          items:
            $ref: '#/components/schemas/NodeBase'
    NodeBase:
      type: object
      properties:
        code:
          type: string
        url:
          type: string
          format: uri
        title:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
security:
  - Token: []