# Generated by Django 2.2.13 on 2021-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0039_auto_20200319_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionnew',
            name='decision_making',
            field=models.CharField(blank=True, choices=[('PROGRAM_MODIFICATION', 'Program modification'), ('DISCHARGE', 'Discharge'), ('TEACHING_SUPPLY', 'Teaching supply'), ('AUTHORITY_OR_SABBATICAL_TEACHING_SUPPLY', 'Authority/sabbatical teaching supply'), ('DEMAND_FOR_DISCHARGE', 'Demand for discharge'), ('DEMAND_FOR_CO_HOLDER', 'Demand for co-holder'), ('CO_HOLDER', 'Co-holder'), ('TO_DELETE', 'To delete'), ('PART_TIME_TEACHING_SUPPLY', 'Part-time teaching supply')], default='', max_length=30),
        ),
    ]
