# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-30 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0380_auto_20181030_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationgroupyear',
            unique_together=set([('education_group', 'academic_year')]),
        ),
        migrations.AlterUniqueTogether(
            name='learningunityear',
            unique_together=set([('learning_unit', 'academic_year'), ('acronym', 'academic_year')]),
        ),
    ]
