# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-31 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0380_auto_20181030_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=40, verbose_name='acronym'),
        ),
    ]
