# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-12 11:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0383_organizationaddress_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisiteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('group_number', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit')),
            ],
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='main_operator',
            field=models.CharField(choices=[('OR', 'OR'), ('AND', 'AND')], default='AND', max_length=5),
        ),
        migrations.AddField(
            model_name='prerequisiteitem',
            name='prerequisite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Prerequisite'),
        ),
        migrations.AlterUniqueTogether(
            name='prerequisiteitem',
            unique_together=set([('prerequisite', 'learning_unit'), ('prerequisite', 'group_number', 'position')]),
        ),
    ]
