# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0387_auto_20181112_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedrelationship',
            name='max_count_authorized',
            field=models.CharField(choices=[('ZERO', 'ZERO'), ('ONE', 'ONE'), ('MANY', 'MANY')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='authorizedrelationship',
            name='min_count_authorized',
            field=models.CharField(choices=[('ZERO', 'ZERO'), ('ONE', 'ONE'), ('MANY', 'MANY')], max_length=5, null=True),
        ),
    ]
