# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0388_auto_20181109_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedrelationship',
            name='max_count_authorized',
            field=models.CharField(choices=[('1', '1'), ('MANY', 'MANY')], default='MANY', max_length=5),
        ),
        migrations.AddField(
            model_name='authorizedrelationship',
            name='min_count_authorized',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=5),
        ),
    ]