# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-19 14:07
from __future__ import unicode_literals

import uuid

from django.db import migrations


def generate_uuids(apps, schema_editor):
    for model_str in ['EducationGroup', 'EducationGroupYear', 'EducationGroupType']:
        model_cls = apps.get_model('base', model_str)
        for row in model_cls.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0392_auto_20181119_1406'),
    ]

    operations = [
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),
    ]
