# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-20 09:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0396_auto_20181119_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('INTERNSHIP', 'Internship'), ('DISSERTATION', 'Dissertation'), ('OTHER_COLLECTIVE', 'Other collective'), ('OTHER_INDIVIDUAL', 'Other individual'), ('MASTER_THESIS', 'Master thesis'), ('EXTERNAL', 'External')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^[BLMWX][A-Z]{2,4}\\d{4}[A-Z0-9]{0,1}$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500)], verbose_name='Credits'),
        ),
    ]
