# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-28 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0400_auto_20181121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(choices=[('DELIBERATION', 'Deliberation'), ('DISSERTATION_SUBMISSION', 'Dissertation submission'), ('EXAM_ENROLLMENTS', 'Exam enrollments'), ('SCORES_EXAM_DIFFUSION', 'Scores exam diffusion'), ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'), ('TEACHING_CHARGE_APPLICATION', 'Teaching charge application'), ('COURSE_ENROLLMENT', 'Course enrollment'), ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'), ('EDUCATION_GROUP_EDITION', 'Education group edition'), ('TESTING', 'Testing'), ('RELEASE', 'Release')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('SECTOR', 'Sector'), ('FACULTY', 'Faculty'), ('SCHOOL', 'School'), ('INSTITUTE', 'Institute'), ('POLE', 'Pole'), ('DOCTORAL_COMMISSION', 'Doctoral commission'), ('PLATFORM', 'Platform'), ('LOGISTICS_ENTITY', 'Logistics entity')], db_index=True, default='', max_length=50, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupachievement',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='educationgroupdetailedachievement',
            unique_together=set([]),
        ),
    ]
