# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0401_auto_20181128_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenrollment',
            name='date_enrollment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
