# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0404_auto_20181129_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='joint_diploma',
            field=models.BooleanField(default=False, verbose_name='Joint diploma'),
        ),
    ]
