# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0405_auto_20181130_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollment',
            name='date_enrollment',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'inscription"),
        ),
    ]
