# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0405_auto_20181130_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='education_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupType', verbose_name='Type of training'),
        ),
    ]
