# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-04 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0407_auto_20181203_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='joint_diploma',
            field=models.BooleanField(default=False, verbose_name='Leads to diploma/certificate'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='other_campus_activities',
            field=models.CharField(blank=True, choices=[('YES', 'yes'), ('NO', 'no'), ('OPTIONAL', 'optional')],
                                   max_length=20, null=True, verbose_name='Activities on other campus'),
        ),
    ]
