# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0408_auto_20181204_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycontaineryear',
            name='type',
            field=models.CharField(choices=[('REQUIREMENT_ENTITY', 'Requirement entity'), ('ALLOCATION_ENTITY', 'Attribution entity'), ('ADDITIONAL_REQUIREMENT_ENTITY_1', 'Additional requirement entity 1'), ('ADDITIONAL_REQUIREMENT_ENTITY_2', 'Additional requirement entity 2')], max_length=35),
        ),
    ]
