# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-07 11:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0408_educationgrouppublicationcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='ARES_GRACA',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES-GRACA'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='ARES_ability',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES ability'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='ARES_study',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='ARES study code'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='co_graduation',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Co-graduation'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='co_graduation_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Co-graduation coefficient'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='web_re_registration',
            field=models.BooleanField(default=True, verbose_name='Web re-registration'),
        ),
    ]
