# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0411_auto_20181210_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='specific_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='French title proper'),
        ),
    ]
