# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0412_auto_20181211_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='publication_contact_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Entity', verbose_name='Publication contact entity'),
        ),
    ]
