# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-12 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0414_educationgroupyear_publication_contact_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgrouppublicationcontact',
            name='role_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='role (english)'),
        ),
        migrations.AlterField(
            model_name='educationgrouppublicationcontact',
            name='role_fr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='role (french)'),
        ),
    ]
