# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0419_auto_20181217_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizedrelationship',
            name='reference',
            field=models.BooleanField(default=False, help_text='True when the relation is authorized for reference link.', verbose_name='Reference'),
        ),
    ]
