# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-18 16:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0419_auto_20181217_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncondition',
            name='education_group_year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_condition', to='base.EducationGroupYear'),
        ),
    ]
