# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0420_authorizedrelationship_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgrouppublicationcontact',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='access_condition',
            field=models.BooleanField(default=False, verbose_name='Access condition'),
        ),
    ]
