# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


def set_many(apps, _):
    AuthorizedRelationship = apps.get_model('base', 'authorizedrelationship')
    for rel in AuthorizedRelationship.objects.all():
        if rel.max_count_authorized == 'MANY':
            rel.max_count_authorized = None
            rel.save()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0423_remove_authorizedrelationship_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizedrelationship',
            name='max_count_authorized',
            field=models.CharField(blank=True, null=True, choices=[('1', 'One'), ('MANY', 'Many')], default='MANY',
                                   max_length=5),
        ),

        migrations.RunPython(set_many),

        migrations.AlterField(
            model_name='authorizedrelationship',
            name='max_count_authorized',
            field=models.PositiveIntegerField(blank=True, help_text='A null value means many relationships.', null=True,
                                              verbose_name='Maximum number of permitted relationships'),
        ),
        migrations.AlterField(
            model_name='authorizedrelationship',
            name='min_count_authorized',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum number of permitted relationships'),
        ),
    ]
