# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0425_auto_20190116_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='linked_with_epc',
            field=models.BooleanField(default=False, verbose_name='Linked with EPC'),
        ),
    ]
