# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-11 10:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0429_auto_20190208_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='initial_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
