# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 16:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0432_auto_20190222_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationrule',
            name='help_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='english help text'),
        ),
        migrations.AlterField(
            model_name='validationrule',
            name='help_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='french help text'),
        ),
    ]
