# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-05 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0433_auto_20190305_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmanager',
            name='education_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroup'),
        ),
    ]
