# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190306_1835'),
        ('base', '0433_auto_20190305_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='isced_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.DomainIsced', verbose_name='ISCED domain'),
        ),
    ]
