# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-13 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0435_educationgroupyear_isced_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationgroupyear',
            name='co_graduation',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, verbose_name='Code co-graduation inter CfB'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='co_graduation_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Co-graduation total coefficient'),
        ),
    ]
