# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-15 15:51
from __future__ import unicode_literals

import base.models.group_element_year
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0436_auto_20190313_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='block',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[base.models.group_element_year.validate_block_value], verbose_name='Block'),
        ),
    ]
