# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-15 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0436_auto_20190313_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^[BEGLMTWX][A-Z]{2,4}\\d{4}')], verbose_name='Code'),
        ),
    ]
