# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0437_auto_20190318_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='managed_entities',
            field=models.ManyToManyField(through='base.EntityManager', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='teachingmaterial',
            name='mandatory',
            field=models.BooleanField(verbose_name='Mandatory'),
        ),
        migrations.AlterField(
            model_name='teachingmaterial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
