# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0438_auto_20190318_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='managed_entities',
            field=models.ManyToManyField(through='base.EntityManager', to='base.Entity'),
        ),
    ]
