# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0438_auto_20190318_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrule',
            name='placeholder',
            field=models.CharField(blank=True, max_length=15, verbose_name='Placeholder'),
        ),
    ]
