# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0443_add_field_learning_unit_year'),
    ]

    operations = [
        migrations.RunSQL(
            """
                with all_learning_unit_components AS (
                    select learning_unit_year_id, learning_component_year_id from base_learningunitcomponent
                )
                
                update base_learningcomponentyear
                set learning_unit_year_id = all_learning_unit_components.learning_unit_year_id 
                from base_learningcomponentyear as lcy
                join all_learning_unit_components on all_learning_unit_components.learning_component_year_id = lcy.id
            """
        ),
    ]
