# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0449_auto_20190423_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_current_partner',
            field=models.BooleanField(default=False, verbose_name='Is current partner'),
        ),
    ]
