# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-06 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0450_organization_is_current_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(choices=[('COURSE', 'Course'), ('INTERNSHIP', 'Internship'), ('DISSERTATION', 'Dissertation'), ('OTHER_COLLECTIVE', 'Other collective'), ('OTHER_INDIVIDUAL', 'Other individual'), ('MASTER_THESIS', 'Thesis'), ('EXTERNAL', 'External')], db_index=True, max_length=20, verbose_name='Type'),
        ),
    ]
