# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0451_auto_20190506_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information')), 'verbose_name': 'Education group'},
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_date', 'Can edit learning unit date'), ('can_edit_learningunit', 'Can edit learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'), ('can_propose_learningunit', 'Can propose learning unit '), ('can_create_learningunit', 'Can create learning unit'), ('can_consolidate_learningunit_proposal', 'Can consolidate learning unit proposal')), 'verbose_name': 'Learning unit'},
        ),
        migrations.AlterModelOptions(
            name='learningunityear',
            options={'ordering': ('acronym',), 'permissions': (('can_receive_emails_about_automatic_postponement', 'Can receive emails about automatic postponement'),), 'verbose_name': 'Learning unit year'},
        ),
    ]
