# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-10 09:23
from __future__ import unicode_literals

import base.models.learning_unit_year
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0451_auto_20190506_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information')), 'verbose_name': 'Education group'},
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_date', 'Can edit learning unit date'), ('can_edit_learningunit', 'Can edit learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'), ('can_propose_learningunit', 'Can propose learning unit '), ('can_create_learningunit', 'Can create learning unit'), ('can_consolidate_learningunit_proposal', 'Can consolidate learning unit proposal')), 'verbose_name': 'Learning unit'},
        ),
        migrations.AlterModelOptions(
            name='learningunityear',
            options={'ordering': ('acronym',), 'permissions': (('can_receive_emails_about_automatic_postponement', 'Can receive emails about automatic postponement'),), 'verbose_name': 'Learning unit year'},
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='educationgrouplanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.Language'),
        ),
        migrations.AlterField(
            model_name='educationgrouporganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear', verbose_name='validity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='administration_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administration_entity', to='base.Entity', verbose_name='Administration entity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='enrollment_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='base.Campus', verbose_name='Enrollment campus'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='main_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Domain', verbose_name='main domain'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='main_teaching_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching', to='base.Campus', verbose_name='Learning location'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='management_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_entity', to='base.Entity', verbose_name='Management entity'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='primary_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Language', verbose_name='Primary language'),
        ),
        migrations.AlterField(
            model_name='educationgroupyear',
            name='publication_contact_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Entity', verbose_name='Publication contact entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='entitymanager',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entitymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='learning_unit_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.LearningUnitEnrollment'),
        ),
        migrations.AlterField(
            model_name='examenrollmenthistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='externallearningunityear',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='externaloffer',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.Domain'),
        ),
        migrations.AlterField(
            model_name='externaloffer',
            name='grade_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.GradeType'),
        ),
        migrations.AlterField(
            model_name='externaloffer',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.OfferYear'),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear'),
        ),
        migrations.AlterField(
            model_name='learningunitenrollment',
            name='offer_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.OfferEnrollment'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.AcademicYear', validators=[base.models.learning_unit_year.academic_year_validator], verbose_name='Academic year'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Campus', verbose_name='Learning location'),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='mandatary',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='offerenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='personentity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='programmanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='proposallearningunit',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
        migrations.AlterField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Person'),
        ),
    ]
