# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0452_auto_20190510_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupelementyear',
            unique_together=set([('parent', 'child_leaf'), ('parent', 'child_branch')]),
        ),
    ]
