# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-10 09:35
from __future__ import unicode_literals

import base.models.learning_component_year
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0452_auto_20190510_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'), ('change_commonpedagogyinformation', 'Can change common pedagogy information'), ('change_pedagogyinformation', 'Can change pedagogy information')), 'verbose_name': 'Education group'},
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_access_learningunit', 'Can access learning unit'), ('can_edit_learningunit_date', 'Can edit learning unit date'), ('can_edit_learningunit', 'Can edit learning unit'), ('can_edit_learningunit_pedagogy', 'Can edit learning unit pedagogy'), ('can_edit_learningunit_specification', 'Can edit learning unit specification'), ('can_delete_learningunit', 'Can delete learning unit'), ('can_propose_learningunit', 'Can propose learning unit '), ('can_create_learningunit', 'Can create learning unit'), ('can_consolidate_learningunit_proposal', 'Can consolidate learning unit proposal')), 'verbose_name': 'Learning unit'},
        ),
        migrations.AlterModelOptions(
            name='learningunityear',
            options={'ordering': ('acronym',), 'permissions': (('can_receive_emails_about_automatic_postponement', 'Can receive emails about automatic postponement'),), 'verbose_name': 'Learning unit year'},
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='repartition_volume_additional_entity_1',
            field=base.models.learning_component_year.RepartitionVolumeField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='repartition_volume_additional_entity_2',
            field=base.models.learning_component_year.RepartitionVolumeField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='repartition_volume_requirement_entity',
            field=base.models.learning_component_year.RepartitionVolumeField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
