# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0457_message_template_egys_automatic_postponement_update'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together=set([('academic_year', 'title')]),
        ),
    ]
