# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-30 11:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0465_message_template_egys_automatic_postponement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposallearningunit',
            name='folder_id',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
