# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-19 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0467_create_permission_person_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningunityear',
            options={'ordering': ('academic_year', 'acronym'), 'permissions': (('can_receive_emails_about_automatic_postponement', 'Can receive emails about automatic postponement'),), 'verbose_name': 'Learning unit year'},
        ),
    ]
