# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-05 14:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0472_auto_20190807_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='data_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_academic_calendar_data', to='base.AcademicYear'),
        ),
    ]
