# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-09-04 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0475_auto_20190829_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningunit',
            old_name='new_end_year',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='learningunit',
            old_name='new_start_year',
            new_name='start_year',
        ),
    ]
