# Generated by Django 2.2.5 on 2020-01-06 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0489_auto_20191217_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningachievement',
            name='annual_id',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
