# Generated by Django 2.2.5 on 2020-01-02 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0489_auto_20191217_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningclassyear',
            name='acronym',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='learningclassyear',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
