# Generated by Django 2.2.5 on 2020-01-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0490_auto_20200102_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningclassyear',
            options={},
        ),
    ]
