# Generated by Django 2.2.5 on 2020-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0493_auto_20200106_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningachievement',
            name='code_name',
            field=models.CharField(max_length=100, null=True, verbose_name='code'),
        ),
        migrations.RunSQL(
            sql="UPDATE base_learningachievement SET code_name=NULL where code_name='.' or code_name=''",
            reverse_sql="UPDATE base_learningachievement SET code_name='.' where code_name is NULL"
        ),
    ]
