# Generated by Django 2.2.5 on 2020-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0497_auto_20200108_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningachievement',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='label',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Professional', 'Professional')], default='Professional', max_length=20),
        ),
    ]
