# Generated by Django 2.2.5 on 2020-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0502_auto_20200128_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaddress',
            name='label',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('PROFESSIONAL', 'Professional')], default='Professional', max_length=20),
        ),
    ]
