# Generated by Django 2.2.10 on 2020-03-19 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0507_auto_20200316_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunityear',
            name='acronym',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator('^[BEGLMTWX][A-Z]{2,4}[1-9]\\d{3}')], verbose_name='Code'),
        ),
    ]
