# Generated by Django 2.2.13 on 2020-07-01 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0509_studentspecificprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='subtype_disability',
            field=models.CharField(blank=True, choices=[('REDUCED_MOBILITY', 'Person with reduced mobility'), ('OTHER_DISABILITY', 'Other special needs')], max_length=20, verbose_name='Sub type Disability'),
        ),
        migrations.AlterField(
            model_name='studentspecificprofile',
            name='type',
            field=models.CharField(choices=[('NOT_DEFINED', 'Not defined'), ('DISABILITY', 'DDI'), ('SPORT', 'Sport'), ('ARTIST', 'Artist'), ('ENTREPRENEUR', 'Entrepreneur'), ('ARRANGEMENT_JURY', 'Educational facilities accepted by Jury')], max_length=20),
        ),
    ]
