# Generated by Django 2.2.10 on 2020-09-17 14:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0511_add_more_decimal_co_graduation_coeff'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentspecificprofile',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
