# Generated by Django 2.2.10 on 2020-04-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0513_auto_20200424_1417'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupelementyear',
            constraint=models.CheckConstraint(check=models.Q(('child_branch__isnull', False), ('child_leaf__isnull', False), _negated=True), name='child_branch_xor_child_leaf'),
        ),
    ]
