# Generated by Django 2.2.10 on 2020-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0514_auto_20200429_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='block',
            field=models.IntegerField(blank=True, null=True, verbose_name='Block'),
        ),
    ]
