# Generated by Django 2.2.13 on 2020-09-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0535_auto_20200908_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'permissions': (('can_access_organization', 'Can access organization'),)},
        ),
    ]
