# Generated by Django 2.2.13 on 2020-09-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0536_studentspecificprofile_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmanager',
            options={'verbose_name': 'Program manager', 'verbose_name_plural': 'Program managers'},
        ),
    ]
