# Generated by Django 3.1.1 on 2020-10-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0537_auto_20200923_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmanager',
            options={'verbose_name': 'Program manager', 'verbose_name_plural': 'Program managers'},
        ),
    ]
