# Generated by Django 3.1.1 on 2020-10-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0539_auto_20201006_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymanager',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity'),
        ),
        migrations.AlterField(
            model_name='entitymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person'),
        ),
    ]
