# Generated by Django 3.1.1 on 2020-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0547_replace_obsolet_decree_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='source',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('DISSERTATION', 'Dissertation'), ('INTERNSHIP', 'Internship')], default='BASE', max_length=25, null=True),
        ),
    ]
