# Generated by Django 2.2.13 on 2021-01-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0551_remarks_annualized'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='other_remark_english',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Other remark in english (intended for publication)'),
        ),
    ]
