# Generated by Django 2.2.13 on 2021-01-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0554_remove_in_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmanager',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
