# Generated by Django 2.2.13 on 2021-01-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0554_auto_20210111_0939'),
        ('base', '0554_remove_in_charge'),
    ]

    operations = [
    ]
