# Generated by Django 2.2.13 on 2021-01-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0556_remove_in_charge_fix'),
        ('base', '0554_learningunityear_other_remark_english'),
    ]

    operations = [
    ]
