# Generated by Django 2.2.13 on 2021-01-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0556_remove_in_charge_fix'),
        ('base', '0555_copy_reddot_information'),
    ]

    operations = [
    ]
