# Generated by Django 2.2.13 on 2021-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0557_learningunityear_other_remark_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='other_remark',
        ),
    ]
