# Generated by Django 2.2.13 on 2021-01-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0561_auto_20210127_1350'),
        ('base', '0561_auto_20210127_1512'),
    ]

    operations = [
    ]
