# Generated by Django 2.2.13 on 2021-01-26 08:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0561_auto_20210127_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupelementyear',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='comment_english',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='english comment'),
        ),
    ]
