# Generated by Django 2.2.13 on 2021-02-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0561_auto_20210127_1512'),
        ('base', '0562_auto_20210128_1416'),
    ]

    operations = [
    ]
