# Generated by Django 2.2.13 on 2021-01-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0563_sessionexam_education_group_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerenrollment',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
