# Generated by Django 2.2.13 on 2021-02-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0564_auto_20210128_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeryear',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='country',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='entity_administration',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='entity_administration_fac',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='entity_management',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='entity_management_fac',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='offeryear',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='offeryeardomain',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='offeryeardomain',
            name='offer_year',
        ),
        migrations.AlterUniqueTogether(
            name='offeryearentity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='offeryearentity',
            name='education_group_year',
        ),
        migrations.RemoveField(
            model_name='offeryearentity',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='offeryearentity',
            name='offer_year',
        ),
        migrations.RemoveField(
            model_name='offerenrollment',
            name='offer_year',
        ),
        migrations.RemoveField(
            model_name='offeryearcalendar',
            name='offer_year',
        ),
        migrations.RemoveField(
            model_name='sessionexam',
            name='offer_year',
        ),
        migrations.AlterUniqueTogether(
            name='programmanager',
            unique_together={('person', 'education_group')},
        ),
        migrations.DeleteModel(
            name='ExternalOffer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferType',
        ),
        migrations.DeleteModel(
            name='OfferYearDomain',
        ),
        migrations.DeleteModel(
            name='OfferYearEntity',
        ),
        migrations.RemoveField(
            model_name='programmanager',
            name='offer_year',
        ),
        migrations.DeleteModel(
            name='OfferYear',
        ),
    ]
